---
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    env_file:
      - stack.env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /configurations/bind9/config:/etc/bind
      - /configurations/bind9/cache:/var/cache/bind
      - /configurations/bind9/records:/var/lib/bind
    restart: always