#cloud-config
users:
  - name: ${username}
    groups: sudo, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_import_id:
      - gh:HarmonicColt4

groups:
  - docker

timezone: Pacific/Auckland

hostname: ${hostname}

packages:
  - qemu-guest-agent
  - net-tools
  - zsh
  - avahi-daemon
    
runcmd:
    - runuser ${username} -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - chsh -s $(which zsh) ${username}
    - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && rm kubectl    
    - cd /home/${username}
    - runuser ${username} -c "git clone https://github.com/HarmonicColt4/dotfiles.git"
    - runuser ${username} -c "ln -sf dotfiles/.zshrc .zshrc"
    - runuser ${username} -c "ln -sf dotfiles/.gitconfig .gitconfig"
    - runuser ${username} -c "minikube start"
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/cloud-config.done