#cloud-config
users:
  - default
  - name: gpenda
    groups:
      - sudo
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPsDjhnlAnvsgNDg6vtmvczoF5BtO2gVEUDonYpBDz1v
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    - apt update
    - apt install -y qemu-guest-agent net-tools
    - timedatectl set-timezone Pacific/Auckland
    - apt install -y zsh
    - runuser gpenda -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - chsh -s $(which zsh) gpenda
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/cloud-config.done