version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - stack.env
    volumes:
      - "/configurations/vaultwarden:/data"
    networks:
      - other
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.weirdrussianserver.xyz`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=production"
      # - "traefik.http.services.vaultwarden.loadbalancer.server.port=8443"
      # - "traefik.http.services.vaultwarden.loadbalancer.server.scheme=https"

networks:
  other:
    external: true
