---
services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-server
    user: 3001:3001
    networks:
      - other
    # ports:
    #   - '5006:5006'
    volumes:
      - "/configurations/actual-server:/data"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-server.rule=Host(`actual-server.weirdrussianserver.xyz`)"
      - "traefik.http.routers.actual-server.entrypoints=websecure"
      - "traefik.http.routers.actual-server.tls.certresolver=production"
      - "traefik.http.services.actual-server.loadbalancer.server.port=5006"

networks:
  other:
    external: true