#cloud-config
users:
  - name: ${username}
    groups: sudo, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_import_id:
      - gh:HarmonicColt4

groups:
  - docker

timezone: Pacific/Auckland

hostname: ${hostname}

packages:
  - qemu-guest-agent
  - net-tools
  - zsh
  - avahi-daemon
    
runcmd:
    - runuser ${username} -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - chsh -s $(which zsh) ${username}
    - curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/cloud-config.done