---
services:
  prowlarr-media:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-media
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    volumes:
      - "/configurations/prowlarr-media:/config"
    networks:
      - media
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-media.rule=Host(`prowlarr-media.weirdrussianserver.xyz`)"
      - "traefik.http.routers.prowlarr-media.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-media.tls.certresolver=production"

  prowlarr-other:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-other
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    volumes:
      - "/configurations/prowlarr-other:/config"
    networks:
      - downloads
    # ports:
    #   - 9696:9696
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr-other.rule=Host(`prowlarr-other.weirdrussianserver.xyz`)"
      - "traefik.http.routers.prowlarr-other.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-other.tls.certresolver=production"

networks:
  media:
    external: true
  downloads:
    external: true