---
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    env_file:
      - stack.env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "$CONF_FOLDER/bind9/config:/etc/bind"
      - "$CONF_FOLDER/bind9/cache:/var/cache/bind"
      - "$CONF_FOLDER/bind9/records:/var/lib/bind"
    restart: always