---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    volumes:
      - $CONF_FOLDER/radarr:/config
      - movies:/movies #optional
    networks:
      - media
    # ports:
    #   - 7878:7878
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.$DOMAIN`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls.certresolver=production"
      # - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    volumes:
      - $CONF_FOLDER/sonarr:/config
      - series:/series #optional
    networks:
      - media
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.$DOMAIN`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=production"

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    volumes:
      - $CONF_FOLDER/sonarr-anime:/config
      - anime:/anime #optional
    networks:
      - media
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr-anime.rule=Host(`sonarr-anime.$DOMAIN`)"
      - "traefik.http.routers.sonarr-anime.entrypoints=websecure"
      - "traefik.http.routers.sonarr-anime.tls.certresolver=production"

  jellyseerr:
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    # ports:
    #   - "5055:5055"
    environment:
      - PUID=3001
      - PGID=3001
      - UMASK=002
      - TZ=Pacific/Auckland
    volumes:
      - $CONF_FOLDER/jellyseerr:/config
    networks:
      - media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.$DOMAIN`)"
      - "traefik.http.routers.jellyseerr.entrypoints=websecure"
      - "traefik.http.routers.jellyseerr.tls.certresolver=production"

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Pacific/Auckland
    networks:
      - media
    # ports:
    #   - "${PORT:-8191}:8191"
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 3001:3001
    networks:
      - media
    volumes:
      - $CONF_FOLDER/recyclarr:/config
    environment:
      - TZ=Pacific/Auckland
    restart: unless-stopped

volumes:
  movies:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/movies"
  series:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/series"
  anime:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/anime"

networks:
  media:
    external: true
