---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=3001
      - PGID=3001
      - TZ=Pacific/Auckland
    networks:
      - postgres
      - other
    volumes:
      - $CONF_FOLDER/nextcloud:/config
      - data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAIN`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=production"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=443"

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":/mnt/storage/nextcloud"

networks:
  postgres:
    external: true
  other:
    external: true