services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
      - other
    restart: unless-stopped
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.$DOMAIN`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=production"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

networks:
  postgres:
    external: true
  other:
    external: true

volumes:
    postgres:
    pgadmin: