---
services:
  qbit-media:
    container_name: qbit-media
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=3001
      - PGID=3001
      - UMASK=002
      - TZ=Pacific/Auckland
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - $CONF_FOLDER/qbit-media:/config
      - movie-torrents:/movies/torrents
      - series-torrents:/series/torrents
      - anime-torrents:/anime/torrents
      # - books-torrents:/books/torrents
    networks:
      - media
    ports:
      - 61917:61917
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit-media.rule=Host(`qbit-media.$DOMAIN`)"
      - "traefik.http.routers.qbit-media.entrypoints=websecure"
      - "traefik.http.routers.qbit-media.tls.certresolver=production"
  qbit-other:
    container_name: qbit-other
    image: ghcr.io/hotio/qbittorrent
    environment:
      - PUID=3001
      - PGID=3001
      - UMASK=002
      - TZ=Pacific/Auckland
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - $CONF_FOLDER/qbit-other:/config
      - downloads:/downloads
    networks:
      - downloads
    ports:
      - 50413:50413
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbit-other.rule=Host(`qbit-other.$DOMAIN`)"
      - "traefik.http.routers.qbit-other.entrypoints=websecure"
      - "traefik.http.routers.qbit-other.tls.certresolver=production"

volumes:

  movie-torrents:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/movies/torrents"
  series-torrents:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/series/torrents"
  anime-torrents:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$MEDIA_NFS_PATH/anime/torrents"
  # books-torrents:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=$NAS_IP,nolock,soft,nfsvers=4
  #     device: ":$MEDIA_NFS_PATH/books/torrents"
  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NAS_IP,nolock,soft,nfsvers=4
      device: ":$DL_NFS_SHARE"

networks:
  media:
    external: true
  downloads:
    external: true