---
networks:
  network:
    external: true
    
services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # - 8080:8080 # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /configurations/traefik:/etc/traefik
    env_file:
      - stack.env
    networks:
      - network
    restart: unless-stopped