---
# -- (Optional) When using a custom network
networks:
  media:
    external: true
  downloads:
    external: true
  other:
    external: true
services:
  traefik:
    image: traefik:v2.11.0
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      # -- (Optional) Enable Dashboard, don't do in production
      - 9090:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - config:/etc/traefik
      - ssl-certs:/ssl-certs
    # -- (Optional) When using Cloudflare as Cert Resolver
    environment:
      - CF_DNS_API_TOKEN=HOS-bLcoKYQ00c88CO_fegBLihq5jr3GTd7dXx7t
    # -- (Optional) When using a custom network
    networks:
      - media
      - downloads
      - other
    restart: unless-stopped

volumes:
  ssl-certs:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.13.25.3,nolock,soft,nfsvers=4
      device: ":/mnt/software/configurations/traefik"